#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

# Enlightn #
cmd="php artisan enlightn"
$cmd
enlightn=$?

# Pint #
cmd="./vendor/bin/pint"
$cmd
pint=$?
 
 
[ $enlightn -eq 0 ] && [ $pint -eq 0 ] && exit 0 || exit 1